"""Interfaz AudioBackend — captura y reproducción agnósticas de plataforma."""
from __future__ import annotations

import asyncio
from typing import Protocol, runtime_checkable


@runtime_checkable
class AudioBackend(Protocol):
    """Backend de audio: captura de micrófono y reproducción de TTS.

    Implementado por SounddeviceBackend (Mac/Linux) y TermuxBackend (Android).
    """

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def get_queue(self) -> asyncio.Queue[bytes]: ...
    def get_oww_queue(self) -> asyncio.Queue[bytes]: ...
    def get_preroll(self) -> bytes: ...
    def is_silence(self, frame: bytes) -> bool: ...
    async def play_notification(self) -> None: ...
    async def play_chunk(self, audio: bytes) -> None: ...
    async def drain(self) -> None: ...
    def reset(self) -> None: ...
